In [1]:
import open3d as o3d
import numpy as np

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [2]:
# pcd = o3d.io.read_point_cloud("copy_of_fragment.pcd")
pcd = o3d.io.read_point_cloud("100.pcd")

In [3]:
type(pcd)

open3d.cpu.pybind.geometry.PointCloud

In [4]:
print(np.asarray(pcd.points))

[[15.36563969 15.55634785  8.61662483]
 [15.37392426 15.46952248  8.59469318]
 [15.40156555 15.4025383   8.58372688]
 ...
 [ 2.88965464 -3.15517545 -1.61464429]
 [ 2.8843565  -3.16885209 -1.61717236]
 [ 2.87524676 -3.17837763 -1.61753345]]


In [5]:
o3d.visualization.draw_geometries([pcd])

In [6]:
pcd.points[0]

array([15.36563969, 15.55634785,  8.61662483])

In [7]:
pcd.points

std::vector<Eigen::Vector3d> with 75537 elements.
Use numpy.asarray() to access data.

In [8]:
pcd.colors

std::vector<Eigen::Vector3d> with 0 elements.
Use numpy.asarray() to access data.